apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud
  template:
    metadata:
      labels:
        app: fraud
    spec:
      containers:
      - name: fraud
        image: finpay/fraud:1.0
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-service
spec:
  selector:
    app: fraud
  ports:
  - port: 9090
    targetPort: 9090
  type: ClusterIP