name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Run tests
        run: |
          cd chapter6-principles/09-continuous-delivery
          go mod init payment
          go test -v

      - name: Build Docker image
        run: |
          cd chapter6-principles/09-continuous-delivery
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/payment:${{ github.sha }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/payment:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubectl
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

      - name: Deploy to Kubernetes
        run: |
          cd chapter6-principles/09-continuous-delivery
          sed -i "s/IMAGE_TAG/${{ github.sha }}/g" k8s/deployment.yaml
          sed -i "s/<YOUR_DOCKERHUB_USERNAME>/${{ secrets.DOCKERHUB_USERNAME }}/g" k8s/deployment.yaml
          kubectl apply -f k8s/deployment.yaml